#!/bin/bash
source "$(dirname $0)/common.sh"

emit_header "C++-related vocabulary"
curl -s https://www.stroustrup.com/glossary.html \
  | pup -p 'b text{}' \
  | grep '[a-zA-Z]' \
  | tr ' ' '\n' \
  | emit_words
