#!/bin/bash
source "$(dirname $0)/common.sh"

emit_header "Git-related vocabulary"
curl -s 'https://raw.githubusercontent.com/git/git/master/Documentation/glossary-content.txt' \
  | egrep -o ']].+::' \
  | tr -d ']:()' \
  | tr ' ' '\n' \
  | emit_words
