#!/bin/bash
source "$(dirname $0)/common.sh"

emit_header "Docker-related vocabulary"
curl -s https://raw.githubusercontent.com/docker/docs/main/data/glossary.yaml \
  | python3 -c 'import sys, yaml, json; json.dump(yaml.safe_load(sys.stdin), sys.stdout)' \
  | jq -r keys[] \
  | emit_words
